"""empty message

Revision ID: 13937d912b7d
Revises: a93489b67bd9
Create Date: 2021-01-31 12:51:25.107110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13937d912b7d'
down_revision = 'a93489b67bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('midify_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('midify_date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('modify_date')

    # ### end Alembic commands ###
